# Database Connection
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/nhatrangstay?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Optional: Hibernate 6 logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# SWAGGER (SPRINGDOC)
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# ===============================
# GOOGLE OAUTH2 (ĐÃ CẬP NHẬT MỚI)
# ===============================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,email,profile

# ===============================
# MAIL CONFIG (GMAIL SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# Ép hiện chi tiết các bước bảo mật ra Terminal
logging.level.org.springframework.security=DEBUG


#Supabase
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_KEY}
supabase.bucket=${SUPABASE_BUCKET}
supabase.service-key=${SUPABASE_SERVICE_KEY}


#SMS
vonage.api.key=${VONAGE_API_KEY}
vonage.api.secret=${VONAGE_API_SECRET}
vonage.sms.from=${VONAGE_SMS_FROM}


openrouter.api.key=${OPENROUTER_API_KEY}

#JWT
jwt.secret=${JWT_SECRET}